# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbda4bc814afd2c6f07128515113a658a64183568b10baea0d9849d1b7c1a2eefed0581ce1d1f1bff5d7f3f1f521b43b96aa95af5d17e22bc00cca2e847b016d

test:
  secret_key_base: 080df63e03f82b90f30cfd4f2c7b48356584e9f90119861572587b10415cb7c8d6df227e05251c3bffb9d5a3ddcd6f0e3942107798611f34761be93887a6abf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
